name: spotify
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: 1.3.0
  spotify_sdk: ^2.3.1
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# 🔹 Solución para el error de "Namespace not specified"
dependency_overrides:
  spotify_sdk:
    git:
      url: https://github.com/brim-borium/spotify_sdk.git
      ref: main
